version: '3.7'

services:
  backend:
    build:
      context: ./backend
    image: starlitskycode/tea-shop-backend:main
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py

  frontend:
    build:
      context: ./frontend
    image: starlitskycode/tea-shop-frontend:main
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
